// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeMcSM_ddhUPTXJXdCZOHhbSzdQ4RQtdI',
    appId: '1:606981267382:web:aec51a8de837bc5a9b6b17',
    messagingSenderId: '606981267382',
    projectId: 'vatruhi-bf024',
    authDomain: 'vatruhi-bf024.firebaseapp.com',
    storageBucket: 'vatruhi-bf024.firebasestorage.app',
    measurementId: 'G-1K20KEZN4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaIpC7gTmPN-KcstSam49Mc3PJtyAKD5A',
    appId: '1:606981267382:android:87b4fdf2f259e90f9b6b17',
    messagingSenderId: '606981267382',
    projectId: 'vatruhi-bf024',
    storageBucket: 'vatruhi-bf024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEcxv2LMPFnup4jJu7r6_dJSwMUqHBTRc',
    appId: '1:606981267382:ios:4433acbdaf6a07209b6b17',
    messagingSenderId: '606981267382',
    projectId: 'vatruhi-bf024',
    storageBucket: 'vatruhi-bf024.firebasestorage.app',
    iosClientId: '606981267382-60tc7bgp89en9uuj0r54ckdp8alm3vo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.maharashtratravelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEcxv2LMPFnup4jJu7r6_dJSwMUqHBTRc',
    appId: '1:606981267382:ios:4433acbdaf6a07209b6b17',
    messagingSenderId: '606981267382',
    projectId: 'vatruhi-bf024',
    storageBucket: 'vatruhi-bf024.firebasestorage.app',
    iosClientId: '606981267382-60tc7bgp89en9uuj0r54ckdp8alm3vo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.maharashtratravelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeMcSM_ddhUPTXJXdCZOHhbSzdQ4RQtdI',
    appId: '1:606981267382:web:d02e4695b0e939939b6b17',
    messagingSenderId: '606981267382',
    projectId: 'vatruhi-bf024',
    authDomain: 'vatruhi-bf024.firebaseapp.com',
    storageBucket: 'vatruhi-bf024.firebasestorage.app',
    measurementId: 'G-Q80Q7Y12WR',
  );
}
